### ISSUE TITLE
뒤집어 엎을까요? 찬/반 투표

### ISSUE THREAD

**Issue by chul0721** [siriushosting/web.html#1]
찬성

**Comment by Mireu-Labcon** [comment]
저는 깔끔하게 만든다면 찬성 합니다
예) 흰배경에 회색 검은색 이 3개 이상의 색이 들어간거 물론 단색

**Comment by JcdeA** [comment]
제가 이미 메인페이지는 아주 대에충 만들어놨어요...

**Comment by chul0721** [comment]
갈아엎을게요.
끝

**Comment by Mireu-Labcon** [comment]
근데 작살내도 시간 내로 가능하죠?

**Comment by juni37** [comment]
전 늦었지만 갈아엎는게 좋을것 같다고 생각합니다아...

**Comment by chul0721** [comment]
> 근데 작살내도 시간 내로 가능하죠?

ㅋ 아마도요
